### ISSUE TITLE
Failed deploy to bluemix - cannot connect with database using ibm_db gem

### ISSUE THREAD

**Issue by griff4692** [ibmdb/ruby-ibmdb#46] opened 2015-12-02 18:41 UTC
hi - I am writing a RoR app with the following in my gemfile and unable to deploy properly to Bluemix.

gem 'ibm_db', '~> 2.5.18'

When I run bundle install I got the following notification:

Successfully installed ibm_db, the Ruby gem for IBM DB2/Informix.  The Ruby gem
is licensed under the MIT License.   The package also includes IBM ODBC and CLI
Driver from IBM, which could have been automatically downloaded as the Ruby gem
is installed on your system/device.   The license agreement to the IBM driver is
 available in the folder "$GEM_HOME/ibm_db-*/lib/clidriver/license".  Check for
additional dependencies, which may come with their own license agreement(s). You
r use of the components of the package and dependencies constitutes your accepta
nce of their respective license agreements.  If you do not accept the terms of a
ny license agreement(s), then delete the relevant component(s) from your system/
device.

My manifest.yml  is as follows:

applications:
- path: .
  memory: 512M
  instances: 1
  domain: mybluemix.net
  name: KnowYourBrand
  host: kyb
  command: bundle exec rake db:setup && bundle exec rails s -p $PORT
  disk_quota: 1024M
  services:
  - Personality Insights-n2
  - Tone Analyzer-uu
  - Insights for Twitter-bt
  - kybSQLDB
  - AlchemyAPI-tw
    buildpack: https://github.com/cloudfoundry/buildpack-ruby.git

The ibm_db directory is saved locally under

C:\Ruby22\lib\ruby\gems\2.2.0\gems\ibm_db-2.5.27-x86-mingw32

---

Here is a clip of my server logs on Bluemix when the deploy fails...

[App/0]
err
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
2015-12-02T12:12:17.223-0600
[App/0]
err
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler.rb:134:in`require'
2015-12-02T12:12:17.223-0600
[App/0]
err
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
2015-12-02T12:12:17.223-0600
[App/0]
err
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in`each'
2015-12-02T12:12:17.223-0600
[App/0]
err
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
2015-12-02T12:12:17.223-0600
[App/0]
err
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in`require'
2015-12-02T12:12:17.223-0600
[App/0]
err
/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
2015-12-02T12:12:17.223-0600
[App/0]
err
LoadError: libdb2.so.1: cannot open shared object file: No such file or directory - /home/vcap/app/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/ibm_db-2.5.27/ibm_db.so

---

Separately if I try to run the command ruby extconf.rb,

C:\Ruby22\lib\ruby\gems\2.2.0\gems\ibm_db-2.5.27-x86-mingw32\ext>ruby extconf.rb

I get the following:

Detected 32-bit Ruby

Environment variable IBM_DB_HOME is not set. Set it to your DB2/IBM_Data_Server_
Driver installation directory and retry gem install.

What seems to be the reason I cannot connect to the database?  This has been an issue I have been unable to resolve for weeks and would love a quick resolution.  Thanks so much!

**Comment by iChicory** [comment] 2015-12-02 18:51
Looks like your build pack does not contains db2 library.
Try to use this build pack: https://github.com/ibmdb/db2rubybuildpack. Uses it for rails applications on Bluemix

**Comment by griff4692** [comment] 2015-12-03 14:23
Hi - I deployed using the buildpack you suggested, but still am having the same issue.  This is the error

LoadError: libdb2.so.1: cannot open shared object file: No such file or directory - /home/vcap/app/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/ibm_db-2.5.27/ibm_db.so

**Comment by griff4692** [comment] 2015-12-03 14:24
Could it have something to do with this...

Environment variable IBM_DB_HOME is not set. Set it to your DB2/IBM_Data_Server_
Driver installation directory and retry gem install.

**Comment by cwilcox4ibm** [comment] 2015-12-04 19:55
I'm experiencing the same problem (not able to load libdb2.so.1 in my Bluemix app).  I can run my app just fine locally on my laptop.  So installing the ibm_db gem on my laptop includes what's needed from the DB2 client. But when this gem is installed as a result of a cf push of the app to Bluemix (which uses the CloudFoundry ruby buildpack) the gem installation apparently does not properly include the DB2 client component.  Please note that as Bluemix users we have no control over or access to the host where the Bluemix application is staged (so setting IBM_DB_HOME is not relevant in this environment).

**Comment by cwilcox4ibm** [comment] 2015-12-04 20:09
I also tried using the db2rubybuildpack as suggested above but this also did not work.  This resulted in a failure to load OpenSSL.  griff4692 - in order to switch buildpacks I believe that you need to delete your Bluemix App if you had already pushed it with the other buildpack (it seems to remember the original buildpack that you used when you created your app).

Here is the output I got when I used the db2rubybuildpack:
2015-12-04T12:04:48.74-0800 [STG/0]      OUT Submodule path 'compile-extensions': checked out '6f91ed772234bfa0433f467d41e86c8e712466b6'
2015-12-04T12:04:48.90-0800 [STG/0]      OUT -------> Buildpack version 1.2.1
2015-12-04T12:04:50.72-0800 [STG/0]      OUT -----> Compiling Ruby/Rails
2015-12-04T12:04:53.44-0800 [STG/0]      OUT -----> Using Ruby version: ruby-2.0.0
2015-12-04T12:04:53.58-0800 [STG/0]      OUT ###### WARNING:
2015-12-04T12:04:53.58-0800 [STG/0]      OUT        Removing `Gemfile.lock` because it was generated on Windows.
2015-12-04T12:04:53.58-0800 [STG/0]      OUT        Bundler will do a full resolve so native gems are handled properly.
2015-12-04T12:04:53.58-0800 [STG/0]      OUT        This may result in unexpected gem versions being used in your app.
2015-12-04T12:04:53.58-0800 [STG/0]      OUT        In rare occasions Bundler may not be able to resolve your dependencies at all.
2015-12-04T12:04:53.58-0800 [STG/0]      OUT        https://devcenter.heroku.com/articles/bundler-windows-gemfile
2015-12-04T12:04:53.59-0800 [STG/0]      OUT -----> Installing dependencies using 1.7.12
2015-12-04T12:04:53.74-0800 [STG/0]      OUT        downloading and untarring DB2 CLI driver....
2015-12-04T12:04:56.68-0800 [STG/0]      OUT        setting DB2 ODBC driver ENV variables
2015-12-04T12:04:57.14-0800 [STG/0]      OUT        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4
2015-12-04T12:04:57.37-0800 [STG/0]      OUT        Could not load OpenSSL.
2015-12-04T12:04:57.42-0800 [STG/0]      OUT        You must recompile Ruby with OpenSSL support or change the sources in your
2015-12-04T12:04:57.42-0800 [STG/0]      OUT        Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using
2015-12-04T12:04:57.42-0800 [STG/0]      OUT        RVM are available at http://rvm.io/packages/openssl.
2015-12-04T12:04:57.45-0800 [STG/0]      OUT        Bundler Output:
2015-12-04T12:04:57.45-0800 [STG/0]      OUT        Could not load OpenSSL.
2015-12-04T12:04:57.45-0800 [STG/0]      OUT        You must recompile Ruby with OpenSSL support or change the sources in your
2015-12-04T12:04:57.45-0800 [STG/0]      OUT        Gemfile from 'https' to 'http'. Instructions for compiling with OpenSSL using
2015-12-04T12:04:57.45-0800 [STG/0]      OUT        RVM are available at http://rvm.io/packages/openssl.
2015-12-04T12:04:57.47-0800 [STG/0]      OUT  !
2015-12-04T12:04:57.47-0800 [STG/0]      OUT  !     Failed to install gems via Bundler.
2015-12-04T12:04:57.47-0800 [STG/0]      OUT  !
2015-12-04T12:04:57.49-0800 [STG/0]      OUT Staging failed: Buildpack compilation step failed
2015-12-04T12:04:57.63-0800 [API/2]      ERR encountered error: App staging failed in the buildpack compile phase

**Comment by arvindgu** [comment] 2015-12-08 07:01
I tried reproducing the problem and I see that this is happening only when ruby version mentioned is 2.1.0 or above. Could you specify the needed Ruby version as 2.0.0 in your Gemfile and give it a try...it will start up successfully.

I am looking into what is happening when deployed to Bluemix when ruby version is 2.1.0 or above.

**Comment by griff4692** [comment] 2015-12-08 15:57
I just switched to Ruby 2.0.0 and having issues installing native gems that require installed build tools (i.e. json).  Will get gems installed and try to push the app again.

**Comment by arvindgu** [comment] 2015-12-09 10:56
Hi,

The ibm_db gem auto downloads the required files while installing the gem. However after ibm_db gem is installed in Bluemix, it is not able to link the downloaded libraries. 

#### To resolve this problem,  please follow below steps.

**Step-1.** While pushing application with migration, pass a command to set  **LD_LIBRARY_PATH** environment variable as below.
> cf push BlogApp2 -c "export LD_LIBRARY_PATH=/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/ibm_db-3.0.0/lib/clidriver/lib:$LD_LIBRARY_PATH; bundle exec rake db:migrate"

**Note :** While running above commad, please specify the Ruby version and ibm_db version that you have specified in gemfile.  You can also refer the path in LoadError: libdb2.so  error message that you see in server logs on Bluemix.

After application is pushed, you will see that migration has run and you will also see database connection error which is expected. 


**Step-2.** Add below Environment Variable in your application. *Login to bluemix -> select your Ruby application -> Click on Environment Variables manu -> Select User defined. -> Add below variable -> Save*.
**Name** - LD_LIBRARY_PATH
**Value** -  /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/ibm_db-3.0.0/lib/clidriver/lib:$LD_LIBRARY_PATH            *[Refer step-1 for the value]*

After adding *LD_LIBRARY_PATH* to your application in Bluemix, you can push your application from cf command as below.

cf push BlogApp2 -c "null"

Now your application will connect to SQLDB.

Thanks,
Arvind

**Comment by arvindgu** [comment] 2015-12-09 11:01
I have verified connectivity to SQLDB with Ruby 2.2.2, Rails 4.2.5 and ibm_db v 3.0.0.

**Comment by griff4692** [comment] 2015-12-10 23:09
i am currently trying to push it right now.  With Ruby 2.2.3, Rails 4.1.8.  When I try to bundle install ibm_db gem with Ruby 2.2.3, however, it returns the error that I have not set the variable IBM_DB_HOME.  I will see if the deploy goes through.  Is there anyway to fix this?

**Comment by arvindgu** [comment] 2015-12-11 06:00
@griff4692 which version of ibm_db gem are you using? Which platform are you running bundle install ibm_db gem command?

**Comment by griff4692** [comment] 2015-12-11 15:30
Running 'gem install ibm_db' from a windows command prompt gives me the error regarding setting my IBM_DB_HOME variable.

**Comment by griff4692** [comment] 2015-12-11 15:31
C:\Users\IBM_ADMIN\Desktop\Projects\KnowYourBrand>gem install ibm_db
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ibm_db:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20151211-9056-3bohz0.rb extconf.rb
Detected 64-bit Ruby

Environment variable IBM_DB_HOME is not set. Set it to your DB2/IBM_Data_Server_
Driver installation directory and retry gem install.


extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ibm_db
-3.0.0 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0
/ibm_db-3.0.0/gem_make.out

**Comment by arvindgu** [comment] 2015-12-11 17:24
@griff4692, ON Windows we support only 32-bit version of ruby. Since you have 64-bit version of ruby, hence you are getting error.
To resolve this, please use 32-bit version of ruby.

**Comment by arvindgu** [comment] 2016-01-04 08:44
Can we close this issue?

**Comment by cwilcox4ibm** [comment] 2016-02-05 01:51
I tried using the solution given above (2 steps).  However, my cf push command fails because it cannot load Ruby:
...
-----> Compiling Ruby/Rails
       Could not get translated url, exited with: DEPENDENCY_MISSING_IN_MANIFEST: https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/ruby-2.2.0.tgz
 !
 !     exit
 !
Staging failed: Buildpack compilation step failed


Apparently the URL to the Ruby tar files has changed (note 'cedar' in this URL that works):
https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar/ruby-2.2.0.tgz

**Comment by arvindgu** [comment] 2016-02-05 04:55
@cwilcox4ibm from above error, it seems you are using a buildpack. To connect to SQLDB, from ruby application you do not need buildpack. Try pushing application again after removing the buildpack.

**Comment by cwilcox4ibm** [comment] 2016-02-05 18:42
I'm not explicitly specifying a buildpack.  I pushed with this command (as documented previously in this thread):
cf push appname -c "export LD_LIBRARY_PATH=/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/ibm_db-3.0.0/lib/clidriver/lib:\$LD_LIBRARY_PATH; bundle exec rake db:migrate"

-------------------------------------------------------------------------------
The command above produced this output:
...
Starting app cvb-tsd-ruby-hw-drda-1 in org cvb@us.ibm.com / space dev as cvb@us.ibm.com...
-----> Downloaded app package (13M)
-----> Downloaded app buildpack cache (74M)
Cloning into '/tmp/buildpacks/ruby-2.2.0'...
fatal: unable to access 'https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar/ruby-2.2.0.tgz/': The requested URL returned error: 403
Cloning into '/tmp/buildpacks/ruby-2.2.0'...
fatal: unable to access 'https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar/ruby-2.2.0.tgz/': The requested URL returned error: 403
/var/vcap/packages/dea_next/buildpacks/lib/git.rb:23:in `clone': Git clone failed: git clone --recursive https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/cedar/ruby-2.2.0.tgz /tmp/buildpacks/ruby-2.2.0 (RuntimeError)
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:154:in `clone_buildpack'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:120:in `build_pack'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:83:in `block in compile_with_timeout'
	from /usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:82:in `compile_with_timeout'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:58:in `block in stage_application'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `chdir'
	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:53:in `stage_application'
	from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'


FAILED
StagingError
...

-------------------------------------------------------------------------------------------
Here is my Gemfile:
source 'https://rubygems.org'
ruby "2.2.0"
gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


gem 'ibm_db', '~> 3.0.0'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

**Comment by cwilcox4ibm** [comment] 2016-02-05 19:05
My Gemfile is this (comments removed):

source 'https://rubygems.org'
ruby "2.2.0"
gem 'rails', '3.2.13'

gem 'ibm_db', '~> 3.0.0'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

**Comment by cwilcox4ibm** [comment] 2016-02-06 00:29
Somehow the cf push command seems to be remembering the buildback.  I had tried using cf push with the -b option to try to get the correct ruby version.  However my original cf push command gave this output (which is why I tried subsequently with -b option):
cf push cvb-tsd-ruby-hw-drda-1 -c "export LD_LIBRARY_PATH=/home/vcap/app/vendor/bundle/ruby/2.2.0/gems/ibm_db-3.0.0/lib/clidriver/lib:\$LD_LIBRARY_PATH; bundle exec rake db:migrate"
...
Starting app cvb-tsd-ruby-hw-drda-1 in org cvb@us.ibm.com / space dev as cvb@us.ibm.com...
-----> Downloaded app package (13M)
-----> Downloaded app buildpack cache (74M)
-------> Buildpack version 1.6.7
-----> Compiling Ruby/Rails
       Could not get translated url, exited with: DEPENDENCY_MISSING_IN_MANIFEST: https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/ruby-2.2.0.tgz
 !
 !     exit
 !
Staging failed: Buildpack compilation step failed

**Comment by arvindgu** [comment] 2016-02-06 09:07
Download the source code of your application from Bluemix. You will find buildpack listed in manifest.yml. Remove the build pack from command and push your application again with this code.

**Comment by cwilcox4ibm** [comment] 2016-02-11 20:53
My application does not have a manifest.yml

**Comment by cwilcox4ibm** [comment] 2016-02-11 21:21
I deleted my Bluemix app and recreated it (it's a Ruby application).  Then I pushed my app and got this error (this is the first error I got before I tried playing around with buildpacks):
...
Starting app cvb-tsd-ruby-hw-drda-1 in org cvb@us.ibm.com / space dev as cvb@us.ibm.com...
-----> Uploading droplet (27M)
-----> Downloaded app package (13M)
-------> Buildpack version 1.6.7
-----> Compiling Ruby/Rails
       Could not get translated url, exited with: DEPENDENCY_MISSING_IN_MANIFEST: https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/ruby-2.2.0.tgz
 !
 !     exit
 !
Staging failed: Buildpack compilation step failed


FAILED
BuildpackCompileFailed
.

**Comment by arvindgu** [comment] 2016-03-09 08:24
@cwilcox4ibm  Try pushing your application with cf command with adding below option

`-b  https://github.com/cloudfoundry/ruby-buildpack.git`

**Closed** 2018-08-17 16:48 UTC
