### ISSUE TITLE
4.0.0 returns a string for database type Date

### ISSUE THREAD

**Issue by sma3** [ibmdb/ruby-ibmdb#84] opened 2019-03-11 17:33 UTC
For a database column defined with datatype Date 3.0.4. returned a ruby Date Object but 4.0.0 returns a String.

**Comment by rs-rappavu** [comment] 2019-03-18 04:49
Will look into it.

**Comment by jfahrenkrug** [comment] 2021-04-29 18:46
@akhilravuri1 Any update on this? I'm also getting a String where I used to get a Date, and I'm on 5.2.0. Is there anything I can do?

**Comment by akhilravuri1** [comment] 2021-04-30 05:53
Hi @jfahrenkrug
Please share your rails version.
A sample program steps which reproduce the issue.

Thanks,
Akhil

**Comment by jfahrenkrug** [comment] 2021-06-10 04:14
Sorry that it took me a while to reply. We are on Rails version 6.0.3, ibm_db gem version 5.2.0. We are using a remote connection to `DB2/SUN64 9.1.9`.

I can't share the whole project, but these are the important parts:

We have a model called `TripVersionDate`:

```
class TripVersionDate < ApplicationRecord
  self.primary_key = 'id'

  default_scope -> { order('from_date, till_date') }

  ## Marks this model as readonly!
  def readonly?
    true
  end
end
```

We use a database view for `trip_version_dates`:

```
CREATE VIEW TRIP_VERSION_DATES AS
        SELECT  khz.lfdnr AS id,
                khz.ab AS from_date,
                khz.bis AS till_date
        FROM KATVERSIONS_Z khz
```

The `KATVERSIONS_Z` table looks like this:

```
db2 DESCRIBE TABLE KATVERSIONS_Z

Column                         Type      Type
name                           schema    name               Length   Scale Nulls
------------------------------ --------- ------------------ -------- ----- ------
LFDNR                          SYSIBM    INTEGER                   4     0 No
AB                             SYSIBM    DATE                      4     0 No
BIS                            SYSIBM    DATE                      4     0 No
```

Clearly the `AB` and `BIS` columns (and the corresponding `from_date` and `till_date` columns of the view) are of type `DATE`. But version 5.2.0 of the ibm_db gem returns Ruby String objects for these columns. Older versions of the gem correctly returned Ruby Date objects for these columns. I can confirm that version `2.5.18` of this gem in connection with Rails `4.1.2` definitely returned `Date` instead of `String`. Thank you for your help!

**Comment by jfahrenkrug** [comment] 2021-06-17 23:50
@bimalkjha @akhilravuri1 I've done some more research into this. Would you be able to mark this issue as "Open" again? Notice the output of `TripVersionDate.columns_hash["from_date"]` (formatted for readability):

```
#<ActiveRecord::ConnectionAdapters::Column:0x0000564258d0d108
@name="from_date",
@sql_type_metadata=#<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x0000564258d0d130 
    @sql_type="date",
    @type="date",
    @limit=10,
    @precision=nil,
    @scale=nil>,
@null=false,
@default=nil,
@default_function="TRIP_VERSION_DATES",
@collation=nil,
@comment=nil>
```

Notice how both `@sql_type` and `@type` correctly say `"date"`. However, when I actually access the value, it comes back as a `String`:

```
td = TripVersionDate.first
td.from_date # => "2019-06-19"
td.from_date.class # => String
```

Any help with this would be greatly appreciated! Thank you :)

**Comment by jfahrenkrug** [comment] 2022-02-03 17:12
@bimalkjha @akhilravuri1 Hi, could you provide any update on this issue? Is this project still actively being worked on or has it been abandoned? Thanks!

**Comment by praveen-db2** [comment] 2022-02-04 10:05
@jfahrenkrug we will shortly start to work on Rails 7.0 with Ruby 3.1.x. Will look into this issue at that time.

**Comment by jfahrenkrug** [comment] 2022-02-04 13:21
@praveen-db2 That's great news, thank you! 🎉

**Comment by matthewkrom** [comment] 2022-03-15 16:30
@jfahrenkrug Have you tried the ActiveRecord type annotations? This exists to correct/adjust/specify data types for fetched activerecord comlumns. e.g.

```
TripVersionDate < ApplicationRecord
   # ... 
  attribute :from_date, :datetime   # or :date or other similar type that works with this gem/environment

end 
```

**Comment by praveen-db2** [comment] 2022-09-21 16:42
@jfahrenkrug I have pushed new version 5.3.1 in support for Rails 6.1 and Ruby 3.0, I had run Rails 6.1 test suite against our ruby IBM_DB adapter and cleared all test cases. Now our adapter is working as per rails test suites. I think this issue should have fixed it. I will be closing this issue, you are free to reopen if you find this issue again.

**Closed by praveen-db2** 2022-09-21 16:42 UTC

**Comment by jfahrenkrug** [comment] 2022-09-26 13:52
@praveen-db2 Great, thanks so much. I will test it and report back.
