### ISSUE TITLE
Load Error Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so (LoadError)

### ISSUE THREAD

**Issue by ejakubowski** [ibmdb/ruby-ibmdb#83] opened 2019-02-26 16:36 UTC
Hello,
I'm trying to run a simple connection test with the ibm_db lib on windows 10 and it keeps failing with the following error.

`
C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: The specified module could not be found.   - C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so (LoadError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/ibm_db.rb:90:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from db2_test.rb:12:in `<main>'
`

Example code:

`require 'rubygems'
require 'mswin32/ibm_db'

conn = IBM_DB.connect("sample", "db2inst1", "mypassword")
`

System Info:
Rails 5.2.2
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
Windows 10 x64
ibm_data_server_client_winx64_v11.1
set IBM_DB_HOME=C:\IBM\SQLLIB
set PATH=%IBM_DB_HOME%\BIN;%PATH%

**Comment by rs-rappavu** [comment] 2019-02-27 14:49
> ibm_data_server_client_winx64_v11.1

Please try using 32 bit version of the ds-driver.

**Comment by ejakubowski** [comment] 2019-02-28 14:22
Nope, still not working.  I removed the x64 client and installed ibm_data_server_client_win32_v11.1.  Not sure if I'm missing something else in the setup?


C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:1: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:2: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:3: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:5: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:6: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:8: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:9: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:10: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:11: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:12: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:13: warning: encountered \r in middle of line, treated as a mere space
C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mswin32/rb2x/i386/ibm_db.so (LoadError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-2.5.18-x86-mingw32/lib/mswin32/ibm_db.rb:10:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from db2_test.rb:12:in `<main>'

**Comment by ejakubowski** [comment] 2019-02-28 14:40
Also below is a better error message, the one I previously sent was when I tried to load the ibm_db gem that came with ibm_data_server_client_win32_v11.1.  Below is with the latest ibm_db gem.

C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: The specified module could not be found.   - C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so (LoadError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/ibm_db.rb:90:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-4.0.0-x86-mingw32/lib/ibm_db.rb:21:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from db2_test.rb:11:in `<main>'

**Comment by rs-rappavu** [comment] 2019-03-01 03:52
You seem to use Ruby version 2.3. Sorry I did not notice it earlier. Please use version 2.2.6. Also for Windows, for require command please specify  - require 'mswin32/ibm_db'

--- copy from my terminal ----
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\rappavu>which irb
C:\Users\rappavu\Work\ruby\install\ruby-2.2.6-i386-mingw32\ruby-2.2.6-i386-mingw32\bin\irb

C:\Users\rappavu>irb
irb(main):001:0> require 'mswin32/ibm_db'
=> true
irb(main):002:0>
---- end ----

**Comment by rs-rappavu** [comment] 2019-03-01 04:10
For Rails, please use version 5.0.7

**Comment by hennooo** [comment] 2019-07-03 09:41
I experience the same issue as @ejakubowski. I'm using the 32-bit DB2 clidriver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/nt32_odbc_cli.zip and tried requiring this gem using Ruby 2.6.3p62 so far. With your suggestion of using Ruby 2.2.6 I cannot even install the gem ibm_db since a requirement of it required Ruby 2.3:
`C:\Users\myuser\Programme\ruby\bin>gem install ibm_db
Fetching: io-like-0.3.0.gem (100%)
Successfully installed io-like-0.3.0
Fetching: archive-zip-0.12.0.gem (100%)
Successfully installed archive-zip-0.12.0
Fetching: arel-9.0.0.gem (100%)
Successfully installed arel-9.0.0
Fetching: concurrent-ruby-1.1.5.gem (100%)
Successfully installed concurrent-ruby-1.1.5
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: tzinfo-1.2.5.gem (100%)
Successfully installed tzinfo-1.2.5
Fetching: i18n-1.6.0.gem (100%)
ERROR:  Error installing ibm_db:
        i18n requires Ruby version >= 2.3.0.`

**Comment by aswerlein511** [comment] 2019-10-02 17:47
I am using Ruby -v 2.5 and tried 2.6.  IBM_DB version 4.0.0 and when I include the require 'mswin32/ibm_db' I am getting the following error:

LoadError (126: The specified module could not be found.   - C:/Ruby26/lib/ruby/gems/2.6.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so)

**Comment by akhilravuri1** [comment] 2020-02-19 07:02
Hi @ejakubowski 

I assume you are installing the ibm_db gem on windows so please set this env variable.
```
set RUBY_DLL_PATH=/path/to/clidriver/bin
example:-
set RUBY_DLL_PATH=C:\Users\rakhil\go_ibm_db\clidriver\bin
```
Thanks,
Akhil

**Comment by akhilravuri1** [comment] 2020-05-12 05:23
closing the issue as the user did not respond.

Thanks,
Akhil

**Closed by akhilravuri1** 2020-05-12 05:23 UTC

**Comment by ThilagaVijay** [comment] 2020-05-14 00:26
Hi Akhilravuri,
Still I am getting the above issue even after setting the class path.
Can you help me...

**Comment by akhilravuri1** [comment] 2020-05-14 02:42
Hi @ThilagaVijay,

Please provide the following details:-

In which platform are you installing the driver?

Are you installing the latest driver? (provide version name)

If windows,

CD to the ruby ibm_db gem installation path  (ex: C:/Ruby26/lib/ruby/gems/2.6.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386) and confirm ibm_db.so file is present.

And the last one please paste the error.


Thanks,
Akhil

**Comment by ericramsey** [comment] 2020-05-15 11:38
@akhilravuri1 
I too am getting the error stating that ibm_db.so is not present. I have checked and made sure that the file is actually located in: C:\Ruby25\lib\ruby\gems\2.5.0\gems\ibm_db-5.0.2-x86-mingw32\lib\mswin32\rb2x\i386
I have also set RUBY_DLL_PATH=C:\PROGRA~1\IBM\SQLLIB\clidriver\bin
can you please explain why I am still receiving this error?

**Comment by akhilravuri1** [comment] 2020-05-18 04:41
Hi @ericramsey 

This is strange in #101 after setting this variable it's working fine.

The only difference is you are using ruby 2.5 and he is using 2.6.6.
@ThilagaVijay  can you confirm which version of ruby are you using?

Thanks,
Akhil

**Comment by ThilagaVijay** [comment] 2020-05-18 14:07
Ruby 2.5

**Comment by ericramsey** [comment] 2020-05-18 14:12
So.. since he is using 2.5 and so am I. any other idea as to why this will not work for me?

**Comment by ThilagaVijay** [comment] 2020-05-18 15:46
It is not working for me either...

**Comment by akhilravuri1** [comment] 2020-05-18 17:38
Hi @ThilagaVijay 

I will install ruby 2.5 and try to reproduce the issue.
You can also build the driver using steps the below steps:-
```
git clone https://github.com/ibmdb/ruby-ibmdb.git
cd rubyibm_source/IBM_DB_Adapter/ibm_db/ext
set IBM_DB_HOME= path/to/clidriver
-$ ruby extconf.rb
- $ ridk exec make
-$ cp rubyibm_source/IBM_DB_Adapter/ibm_db/ext/ibm_db.so to 
    rubyibm_source/IBM_DB_Adapter/ibm_db/lib/mswin32/rb2x/i386
    	
- $ cd rubyibm_source/IBM_DB_Adapter/ibm_db
- $ gem build IBM_DB.gemspec
-$ gem install ibm_db-5.0.2-x86.gem
```

Thanks,
Akhil

**Comment by ThilagaVijay** [comment] 2020-05-26 14:30
Hi Akhil,
 I tried the above steps but end up getting error, let me know what I have
missed ...
[image: image.png]

Thanks
Thilaga

**Comment by ericramsey** [comment] 2020-05-29 11:50
@akhilravuri1 
When i try to execute 'ruby extconf.rb' i am getting a failure. 
Error: Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.
I have attached the mkmf.log file. 
If you could please give some insight as to what I am missing within my setup I would appreciate it. 
[mkmf.log](https://github.com/ibmdb/ruby-ibmdb/files/4701583/mkmf.log)

Could this be because the IBM\SQLLIB\clidriver\bin is a 64bit version?

**Comment by akhilravuri1** [comment] 2020-05-29 11:54
Hi @ericramsey 

Please use 32-bit clidriver.

Thanks,
Akhil
